language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm@6.4.1
cache: npm

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage

notifications:
  email:
    recipients:
      - danielbrutti@gmail.com